### ISSUE TITLE
Book Search - Certain queries make the app crash after pressing the Search button

### ISSUE THREAD

**Issue by chrisvasqm** [chrisvasqm/android-basics#1]
# Steps to reproduce

1. Type in a query, like "car".
2. Tap the Search `Button`.
3. After the results are shown.
4. Close the on screen keyboard.
5. Boom!

# Error log

```
ava.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter $receiver
                      at kotlin.collections.CollectionsKt___CollectionsKt.first(Unknown Source:2)
                      at com.chrisvasqm.androidbasics.adapter.BookAdapter.getView(BookAdapter.kt:20)
```

**Comment by nelcolon** [comment]
Maybe you're passing a null in here.

This may halp.
[](https://stackoverflow.com/questions/44885783/illegalargumentexception-parameter-specified-as-non-null-is-null)

**Comment by chrisvasqm** [comment]
Thanks for replying @nelcolon!

I was going crazy since I was making sure to prevent any `null` values in my Kotlin code, but it turns out that there was nothing "bad" with it, it's just that there are certain books provided by the Google Books API that **do not** have any authors, so that's why I was getting a `null` instead.

I'll commit a fix soon.
